# Generated by Django 2.2.8 on 2020-07-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_age', models.IntegerField()),
                ('label_name', models.CharField(max_length=200)),
                ('artist_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='is_single',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='release date'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=200)),
                ('track_slug', models.CharField(default=1, max_length=200)),
                ('album_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Album', verbose_name='Album')),
                ('artist_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Artist', verbose_name='Artist')),
            ],
            options={
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Genre', verbose_name='Genre'),
        ),
    ]
