# Generated by Django 2.2.8 on 2020-07-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200729_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_name',
            field=models.CharField(max_length=200),
        ),
    ]
