# Generated by Django 2.2.8 on 2020-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200729_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(default=1),
        ),
    ]
