# Generated by Django 2.2.8 on 2020-07-31 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_track_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Dark_Side_of_the_Moon.png/220px-Dark_Side_of_the_Moon.png', max_length=200),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_image',
            field=models.CharField(default='https://img.discogs.com/G0haDbUa-_stv3xTv9R5ip4fAKo=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-238369-1490362449-5582.jpeg.jpg', max_length=200),
        ),
        migrations.CreateModel(
            name='TrackRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(default='')),
                ('track_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Track', verbose_name='Track')),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Album Ratings',
            },
        ),
        migrations.CreateModel(
            name='AlbumRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(default='')),
                ('album_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Album', verbose_name='Album')),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Album Ratings',
            },
        ),
    ]
