# Generated by Django 2.2.8 on 2020-08-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200731_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackrating',
            options={'verbose_name_plural': 'Track Ratings'},
        ),
        migrations.AddField(
            model_name='track',
            name='track_lyrics',
            field=models.TextField(default=''),
        ),
    ]
